package com.termx.app.pkg

import android.content.Context
import android.util.Log
import java.io.*

/**
 * Installs the bootstrap base system for TermX.
 *
 * The bootstrap is the minimal set of files needed for the package manager
 * and terminal to function properly. Without a bootstrap, the terminal can
 * only use Android's built-in /system/bin/sh which lacks many utilities.
 *
 * Bootstrap installs:
 *   - Basic directory structure under $PREFIX
 *   - A minimal shell profile (~/.bashrc, ~/.profile)
 *   - Helper scripts (pkg command, termux-reset, etc.)
 *   - Default termux.properties
 *   - Essential symlinks and configuration
 *
 * In a production build, the bootstrap would also include pre-compiled
 * native binaries (bash, coreutils, etc.) bundled as assets or downloaded
 * from a CDN. For this initial version, we set up the structure and
 * placeholder scripts that will be replaced by real packages from the
 * repository when `pkg install` is run.
 */
object BootstrapInstaller {

    private const val TAG = "BootstrapInstaller"
    private const val PREFIX = TermXPackageManager.PREFIX

    /**
     * Install the bootstrap system.
     * This is idempotent — running it multiple times is safe.
     */
    fun install(context: Context) {
        Log.i(TAG, "Installing bootstrap system...")

        installDirectoryStructure()
        installShellProfiles(context)
        installPkgCommand(context)
        installHelperScripts(context)
        installDefaultConfig(context)

        Log.i(TAG, "Bootstrap installation complete")
    }

    /**
     * Create the full directory structure under $PREFIX.
     */
    private fun installDirectoryStructure() {
        val dirs = listOf(
            // Standard FHS-like layout
            "bin",
            "lib",
            "lib/pkgconfig",
            "include",
            "include/c++",
            "share",
            "share/doc",
            "share/man",
            "share/man/man1",
            "share/man/man3",
            "share/man/man5",
            "share/info",
            "share/aclocal",
            "share/locale",
            "etc",
            "etc/post-install.d",
            "etc/pre-uninstall.d",
            "etc/profile.d",
            "tmp",
            "var",
            "var/log",
            "var/cache",
            "var/lib",
            // Termux-compatible paths
            "home",
            // Development
            "share/cmake",
            "share/pkgconfig"
        )

        for (dir in dirs) {
            val d = File(PREFIX, dir)
            if (!d.exists()) {
                d.mkdirs()
            }
        }

        // Ensure tmp is writable
        File(PREFIX, "tmp").setWritable(true, false)

        Log.d(TAG, "Directory structure created")
    }

    /**
     * Install shell profile files that set up the environment.
     */
    private fun installShellProfiles(context: Context) {
        val homeDir = File(PREFIX, "home")

        // ~/.bashrc
        val bashrc = File(homeDir, ".bashrc")
        if (!bashrc.exists()) {
            bashrc.writeText("""
# TermX Bash Configuration
# Generated by bootstrap installer

# Export essential paths
export PREFIX=$PREFIX
export PATH=$PREFIX/bin:$PREFIX/bin/applets:\$PATH
export LD_LIBRARY_PATH=$PREFIX/lib:\$LD_LIBRARY_PATH
export TERM=xterm-256color
export COLORTERM=truecolor
export LANG=en_US.UTF-8
export HOME=$PREFIX/home
export TMPDIR=$PREFIX/tmp

# Shell options
set -o emacs

# History settings
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoredups:erasedups
shopt -s histappend

# Prompt — shows session info
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# Aliases
alias ll='ls -la'
alias la='ls -a'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias cls='clear'

# TermX helper functions
pkg() {
    termx-pkg "$@"
}

# Welcome message
echo "Welcome to TermX!"
echo "Type 'pkg help' for package management commands."
echo ""
""".trimIndent() + "\n")
        }

        // ~/.profile
        val profile = File(homeDir, ".profile")
        if (!profile.exists()) {
            profile.writeText("""
# TermX Login Profile
# Source .bashrc if running in an interactive shell
if [ -n "$"BASH_VERSION"" ]; then
    if [ -f "$"HOME/.bashrc"" ]; then
        . "$"HOME/.bashrc""
    fi
fi

# Set PATH so it includes TermX bin
if [ -d "$PREFIX/bin" ] ; then
    PATH="$PREFIX/bin:$PREFIX/bin/applets:$PATH"
fi
""".trimIndent() + "\n")
        }

        // /etc/profile
        val etcProfile = File(PREFIX, "etc/profile")
        if (!etcProfile.exists()) {
            etcProfile.writeText("""
# TermX System Profile
export PREFIX=$PREFIX
export PATH=$PREFIX/bin:\$PATH
export LD_LIBRARY_PATH=$PREFIX/lib
export TERM=xterm-256color

# Source all scripts in profile.d
if [ -d $PREFIX/etc/profile.d ]; then
    for script in $PREFIX/etc/profile.d/*.sh; do
        if [ -r "$"script"" ]; then
            . "$"script""
        fi
    done
    unset script
fi
""".trimIndent() + "\n")
        }

        Log.d(TAG, "Shell profiles installed")
    }

    /**
     * Install the `pkg` command script.
     * This is the main entry point for package management from the terminal.
     */
    private fun installPkgCommand(context: Context) {
        val pkgScript = File(PREFIX, "bin/pkg")
        if (!pkgScript.exists()) {
            pkgScript.writeText("""
#!/system/bin/sh
# TermX Package Manager Command
# Usage: pkg <command> [arguments]
#
# Commands:
#   install <packages>   Install packages
#   uninstall <packages> Uninstall packages
#   update               Update package index
#   upgrade              Upgrade installed packages
#   search <query>       Search for packages
#   list                 List installed packages
#   list-all             List all available packages
#   show <package>       Show package details
#   upgradable           List upgradable packages
#   clean                Clean package cache
#   help                 Show this help message

COMMAND="$"1"
shift

case "$"COMMAND"" in
    install|i)
        am broadcast -n com.termx.app/.api.TermXApiReceiver \
            -a com.termx.app.api.PKG_INSTALL \
            --es packages "$*" 2>/dev/null
        echo "Installing: $*"
        echo "Use 'pkg list' to check installation status."
        ;;
    uninstall|remove|rm)
        am broadcast -n com.termx.app/.api.TermXApiReceiver \
            -a com.termx.app.api.PKG_UNINSTALL \
            --es packages "$*" 2>/dev/null
        echo "Removing: $*"
        ;;
    update)
        am broadcast -n com.termx.app/.api.TermXApiReceiver \
            -a com.termx.app.api.PKG_UPDATE 2>/dev/null
        echo "Updating package index..."
        ;;
    upgrade|up)
        am broadcast -n com.termx.app/.api.TermXApiReceiver \
            -a com.termx.app.api.PKG_UPGRADE 2>/dev/null
        echo "Upgrading packages..."
        ;;
    search|s)
        am broadcast -n com.termx.app/.api.TermXApiReceiver \
            -a com.termx.app.api.PKG_SEARCH \
            --es query "$*" 2>/dev/null
        echo "Searching: $*"
        ;;
    list|ls)
        # List installed packages from local DB
        if [ -f /data/data/com.termx.app/files/pkg/installed_packages.json ]; then
            echo "Installed packages:"
            # Simple grep-based listing (proper JSON parsing would need jq)
        else
            echo "No packages installed yet."
        fi
        ;;
    list-all)
        echo "Run 'pkg update' first to fetch the package list."
        ;;
    show|info)
        am broadcast -n com.termx.app/.api.TermXApiReceiver \
            -a com.termx.app.api.PKG_SHOW \
            --es package "$*" 2>/dev/null
        ;;
    upgradable)
        am broadcast -n com.termx.app/.api.TermXApiReceiver \
            -a com.termx.app.api.PKG_UPGRADABLE 2>/dev/null
        ;;
    clean)
        am broadcast -n com.termx.app/.api.TermXApiReceiver \
            -a com.termx.app.api.PKG_CLEAN 2>/dev/null
        echo "Cache cleaned."
        ;;
    help|--help|-h)
        echo "TermX Package Manager"
        echo ""
        echo "Usage: pkg <command> [arguments]"
        echo ""
        echo "Commands:"
        echo "  install <packages>   Install packages"
        echo "  uninstall <packages> Uninstall packages"
        echo "  update               Update package index"
        echo "  upgrade              Upgrade installed packages"
        echo "  search <query>       Search for packages"
        echo "  list                 List installed packages"
        echo "  list-all             List all available packages"
        echo "  show <package>       Show package details"
        echo "  upgradable           List upgradable packages"
        echo "  clean                Clean package cache"
        echo "  help                 Show this help message"
        ;;
    *)
        echo "Unknown command: $COMMAND"
        echo "Run 'pkg help' for usage information."
        exit 1
        ;;
esac
""".trimIndent() + "\n")
            try {
                Runtime.getRuntime().exec(
                    arrayOf("chmod", "755", pkgScript.absolutePath)
                ).waitFor()
            } catch (e: Exception) {
                Log.w(TAG, "chmod failed for pkg: ${e.message}")
            }
        }

        // Also create termx-pkg alias
        val termxPkg = File(PREFIX, "bin/termx-pkg")
        if (!termxPkg.exists()) {
            termxPkg.writeText("#!/system/bin/sh\nexec $PREFIX/bin/pkg \"\$@\"\n")
            try {
                Runtime.getRuntime().exec(
                    arrayOf("chmod", "755", termxPkg.absolutePath)
                ).waitFor()
            } catch (_: Exception) {}
        }

        Log.d(TAG, "pkg command installed")
    }

    /**
     * Install helper scripts.
     */
    private fun installHelperScripts(context: Context) {
        // termux-reset — reset TermX to clean state
        val resetScript = File(PREFIX, "bin/termux-reset")
        if (!resetScript.exists()) {
            resetScript.writeText("""
#!/system/bin/sh
# TermX Reset Script
# Removes all installed packages and resets to bootstrap state.
# WARNING: This is destructive!

echo "WARNING: This will remove all installed packages!"
echo -n "Are you sure? [y/N] "
read answer

if [ "$"answer"" = "y" ] || [ "$"answer"" = "Y" ]; then
    echo "Resetting TermX..."
    rm -rf $PREFIX/bin/*
    rm -rf $PREFIX/lib/*
    rm -rf $PREFIX/include/*
    rm -rf $PREFIX/share/*
    rm -rf $PREFIX/var/*
    rm -rf /data/data/com.termx.app/files/pkg/installed_packages.json
    rm -f /data/data/com.termx.app/files/.bootstrap_version
    echo "Reset complete. Restart TermX to reinstall bootstrap."
else
    echo "Reset cancelled."
fi
""".trimIndent() + "\n")
            try {
                Runtime.getRuntime().exec(
                    arrayOf("chmod", "755", resetScript.absolutePath)
                ).waitFor()
            } catch (_: Exception) {}
        }

        // termux-reload-settings — reload termux.properties
        val reloadScript = File(PREFIX, "bin/termux-reload-settings")
        if (!reloadScript.exists()) {
            reloadScript.writeText("""
#!/system/bin/sh
# Reload TermX settings
am broadcast -n com.termx.app/.api.TermXApiReceiver \
    -a com.termx.app.api.RELOAD_SETTINGS 2>/dev/null
echo "Settings reloaded."
""".trimIndent() + "\n")
            try {
                Runtime.getRuntime().exec(
                    arrayOf("chmod", "755", reloadScript.absolutePath)
                ).waitFor()
            } catch (_: Exception) {}
        }

        Log.d(TAG, "Helper scripts installed")
    }

    /**
     * Install default configuration files.
     */
    private fun installDefaultConfig(context: Context) {
        // Default termux.properties with sensible defaults
        val propsFile = File(context.filesDir, ".termx/termux.properties")
        if (!propsFile.exists()) {
            propsFile.writeText("""
# TermX Configuration File
# This file is loaded on startup and can be reloaded with 'termux-reload-settings'

# Terminal bell character behavior (vibrate/visible/ignore)
bell-character=vibrate

# Back key behavior (escape/back)
back-key=escape

# Default terminal colors (theme name)
# Options: Catppuccin Mocha, Dracula, Monokai, Solarized Dark, Nord
# theme=Catppuccin Mocha

# Extra keys row visibility
extra-keys-style=default

# Custom extra keys layout
# extra-keys=[[ESC, '/', '-', 'HOME', 'UP', 'END', 'PGUP'], ['TAB', 'CTRL', 'ALT', 'LEFT', 'DOWN', 'RIGHT', 'PGDN']]

# Terminal margin (in dp)
# terminal-margin-horizontal=3
# terminal-margin-vertical=0

# Terminal cursor style (block/underline/bar)
# cursor-style=block

# Terminal cursor blink
# cursor-blink=true

# Fullscreen mode
# fullscreen=false

# Default shell
# shell=/data/data/com.termx.app/files/usr/bin/bash

# Initial working directory
# default-dir=/data/data/com.termx.app/files/home

# Allow external applications to run commands
# allow-external-apps=true

# Create login shells
# login-shell=false
""".trimIndent() + "\n")
        }

        Log.d(TAG, "Default config installed")
    }
}
